### ISSUE TITLE
Bigger downloads keep freezing

### ISSUE THREAD

**Issue by AmarilloNL** [Incredibleflamer/Anime-batch-downloader-gui#3]
Hi!

Trying to download all 366 episodes of Bleach but after a while the program stops with downloading doesn't continue.

Maybe a side request: Possible to add a back button? And perhaps a clear queue button.

Regards,
Amarillo

**Comment by Incredibleflamer** [comment]
Sure, I can! I will try to code it as soon as my exams end, around October 24 
Until then, please bear with me 🙏 Sorry!

**Comment by Incredibleflamer** [comment]
💀 i miss clicked mb

**Comment by AmarilloNL** [comment]
No worries, hope to hear from you end of october 👌

**Comment by Incredibleflamer** [comment]
I’ve added a Back Button and the ability to Remove Anime from Queue. Check out the latest release!

**Comment by AmarilloNL** [comment]
Added features are working perfectly. Unfortunately with the update, the program feels a lot slower with booting up, searching animes and downloading. I tested this on my main PC and server with the same sympthomes.

**Comment by Incredibleflamer** [comment]
I agree, the booting speed is slower than expected. This is mainly due to two reasons: the application doesn't run any background services, so it takes a bit longer to boot up compared to normal applications. Secondly, I'm still a noobie in building apps, but don’t worry, I’m going to try to solve the issue in next release!

Also, check out the latest release, which includes a bulk downloader for manga!

**Comment by AmarilloNL** [comment]
Awesome stuff! If you want me as a test user, Add me on discord @Amarillo 
Manga downloader works 👌
